name: firstapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  dartz: ^0.10.1
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
