// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcUK2v9hdUckv55zu_KePEAwpY9XUPme8',
    appId: '1:322415399198:web:69e1dda5a2bfac5061390f',
    messagingSenderId: '322415399198',
    projectId: 'todo-clean-imd-1205',
    authDomain: 'todo-clean-imd-1205.firebaseapp.com',
    storageBucket: 'todo-clean-imd-1205.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1kOqKnO6LtwU_5FKOFVLL-TdYIQrI7UI',
    appId: '1:322415399198:android:0e9c16847cfc13bc61390f',
    messagingSenderId: '322415399198',
    projectId: 'todo-clean-imd-1205',
    storageBucket: 'todo-clean-imd-1205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFuzlnhJoYImwWELT1th6gI3XCTp7askI',
    appId: '1:322415399198:ios:93207cb61cd1df8c61390f',
    messagingSenderId: '322415399198',
    projectId: 'todo-clean-imd-1205',
    storageBucket: 'todo-clean-imd-1205.appspot.com',
    iosBundleId: 'com.imd.firstapp.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFuzlnhJoYImwWELT1th6gI3XCTp7askI',
    appId: '1:322415399198:ios:f58e7a731dc66beb61390f',
    messagingSenderId: '322415399198',
    projectId: 'todo-clean-imd-1205',
    storageBucket: 'todo-clean-imd-1205.appspot.com',
    iosBundleId: 'com.imd.firstapp.firstapp.RunnerTests',
  );
}
